### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by overtube** [poole/hyde#308]
**jekyll serve**

```
/home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:274:in `search_up': undefined method `untaint' for "/home/ui/Templates/poole":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:261:in `find_file'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:253:in `find_gemfile'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb:28:in `root'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:234:in `root'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:246:in `app_config_path'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:273:in `settings'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:84:in `configured_bundle_path'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:351:in `use_system_gems?'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:541:in `configure_gem_path'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:534:in `configure_gem_home_and_path'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:66:in `configure'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:134:in `definition'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.0.2/lib/bundler.rb:101:in `setup'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /home/ui/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/exe/jekyll:11:in `<top (required)>'
	from /home/ui/.rbenv/versions/3.2.2/bin/jekyll:25:in `load'
	from /home/ui/.rbenv/versions/3.2.2/bin/jekyll:25:in `<main>'
```

maybe need change ruby version?

Also I try

**gem install jekyll-theme-poole**

but get that:
```
sass's executable "sass" conflicts with sass-embedded
Overwrite the executable? [yN]  n
ERROR:  Error installing jekyll-theme-poole:
	"sass" from sass conflicts with installed executable from sass-embedded
```
and
**gem install jekyll-theme-lanyon
gem install jekyll-theme-hyde**
and give conflicts with installed executable from **sass-embedded**

**ruby -v**
```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```
**gem -v**
```3.4.14```

**Comment by overtube** [comment]
after install `jekyll-paginate` all worked
